service: bms-fn-put

provider:
  name: aws
  runtime: python3.8
  stage: dev
  memorySize: 512
  timeout: 30
  region: us-east-1
  environment:
    MONGO_DB_USER: dbDeveloper
    MONGO_DB_PASS: MHqaGjazwTDcGbu2
    MONGO_DB_NAME: bmsDB
    MONGO_DB_URL: mycluster.4rkjp.mongodb.net

functions:
  api-putEntity:
    handler: handler.handler
    events:
      - http:
          path: '/entity/{entity+}'
          method: put
          cors: true
